spring.datasource.url=jdbc:postgresql://dpg-d9i51p7avr4c73a5ppog-a.oregon-postgres.render.com:5432/returnsystem_oap1?sslmode=require
spring.datasource.username=returnsystem_oap1_user
spring.datasource.password=jD1SvlAmkZCuJZn8oXduQ8oE6SUUGQAB
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:9090}

spring.thymeleaf.cache=false
spring.mail.host=smtp.gmail.com
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true