spring.datasource.url=jdbc:postgresql://dpg-d7c19sl8nd3s73ckue9g-a.oregon-postgres.render.com:5432/returnsystem?sslmode=require
spring.datasource.username=returnsystem_user
spring.datasource.password=hHp4NTznHONEXQrvNpAMolpWkioM9WfA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}