POST https://return-system-1.onrender.com/api/add
Content-Type: application/json

{
  "returnId": "RET101",
  "orderId": "ORD501",
  "product": "Shoes",
  "reason": "Size issue",
  "sellerEmail": "admin@gmail.com",
  "originalPrice": "1000",
  "currentPrice": "850",
  "salePrice": "900"
}
